package it.akt.model;

public enum Interessi {

	ARTE, MUSICA, CINEMA, LETTERATURA, VIAGGI, CUCINA, SPORT, FOTOGRAFIA, GIARDINAGGIO, LETTURA, SCRITTURA, VIDEOGIOCHI, TECNOLOGIA, MODA, BENESSERE, VOLONTARIATO, STORIA, SCIENZA, ASTRONOMIA, LINGUE
	
}
